### ISSUE TITLE
TTFs

### ISSUE THREAD

**Issue by davelab6** [girish-dalvi/Ek-Mukta#21]
I'll need TTFs to update Google Fonts, but the TTX directory and EkMukta-2.015.zip in https://github.com/girish-dalvi/Ek-Mukta/releases only have OTFs

There are some issues with the name table, I'll send a PR, https://github.com/girish-dalvi/Ek-Mukta/pull/22

**Comment by girish-dalvi** [comment]
Update fixes #21
